theme: jekyll-theme-cayman
title: PySNARK
description: Library for programming SNARKs directly in Python
show_downloads: ["true"]
exclude: ["depends"]

github:
  zip_url: https://github.com/meilof/pysnark/releases/download/0.2.2/PySNARK-0.2.2-nols-win64.zip
  tar_url: https://github.com/meilof/pysnark/releases/download/0.2.2/PySNARK-0.2.2.tar.gz
  version: 0.2.1