theme: jekyll-theme-cayman
title: PySNARK
description: Library for programming SNARKs directly in Python
show_downloads: ["true"]
exclude: ["depends"]

github:
  zip_url: https://github.com/meilof/pysnark/releases/download/0.2.1/PySNARK-0.2.1-nols-win64.zip
  tar_url: PySNARK-0.2.1.tar.gz
  version: 0.2.1